source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]


# --------------------------------------------------------- Dradis dependencies

# Dradis::Core, ::Frontend
gemspec path: 'engines/core'
gemspec path: 'engines/frontend'


# Dradis::Plugins manage the list of available / loaded external plugins
gem 'dradis-plugins', github: 'dradis/dradis-plugins'





# In Production we need to be able to compile assets
# gem 'execjs'
# gem 'therubyracer'

# ------------------------------------------------------------------ Asset gems
gem 'jquery-fileupload-rails'


# ------------------------------------------------------------------ Other gems

# Manipulate XML
gem 'builder'
gem 'nokogiri'

# Textile markup
gem 'RedCloth', '4.2.9', :require => 'redcloth'

# Security
gem 'ruby-nmap'

# To create/read zip archives
gem 'rubyzip', '~> 0.9.6.1'

# Command line interface
gem 'thor', '~> 0.19.1'


# ------------------------------------------------------------------ Test & Dev
# Gems required for testing
gem 'rspec-rails', :group => [:development, :test]

group :test do
  gem 'database_cleaner'
  gem 'factory_girl', '~> 2.6.4'
  gem 'capybara'
  gem 'guard-rspec'
end



# =================================================== Other plugins and engines
# = ~  Do not edit this file!! ~ ==============================================
# =============================================================================
#
# See Gemfile.plugins to edit the list of plugins and tool connectors that will
# be loaded by the framework.
#
# Plugins in Gemfile.plugins will be loaded automatically, that's where your
# own plugins should be listed.
#

plugins_file = 'Gemfile.plugins'
if File.exists?(plugins_file)
  eval(IO.read(plugins_file), binding)
end
