# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "categories", :force => true do |t|
    t.column "name", :string
  end

  create_table "configurations", :force => true do |t|
    t.column "name",  :string
    t.column "value", :string
  end

  create_table "hosts", :force => true do |t|
    t.column "address", :string
  end

  create_table "notes", :force => true do |t|
    t.column "author",           :string
    t.column "category_id",      :integer
    t.column "text",             :text
    t.column "annotatable_id",   :integer
    t.column "annotatable_type", :string
  end

  create_table "protocols", :force => true do |t|
    t.column "name", :string
  end

  create_table "services", :force => true do |t|
    t.column "name",        :string
    t.column "host_id",     :integer
    t.column "port",        :integer
    t.column "protocol_id", :integer, :null => false
  end

  create_table "tickets", :force => true do |t|
    t.column "value",       :string
    t.column "ip",          :string
    t.column "valid_until", :datetime
  end

end
